<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>es.us.isa.httpmutator.experiment.services</groupId>
        <artifactId>mt_jdk8</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>mt-person-controller</artifactId>
    <packaging>jar</packaging>

    <name>mi-person-controller</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <testcontainers.version>1.17.6</testcontainers.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- OpenAPI 3 -->
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-core</artifactId>
                <version>2.2.21</version>
            </dependency>
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-models</artifactId>
                <version>2.2.21</version>
            </dependency>
            <dependency>
                <groupId>io.swagger.parser.v3</groupId>
                <artifactId>swagger-parser</artifactId>
                <version>2.1.22</version>
            </dependency>

            <!-- Swagger 2.x -->
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-core</artifactId>
                <version>1.6.16</version>
            </dependency>
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-models</artifactId>
                <version>1.6.16</version>
            </dependency>
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-parser</artifactId>
                <version>1.0.75</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.mongodb</groupId>
            <artifactId>java-spring-boot-mongodb-starter</artifactId>
            <version>1.0.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <version>2.4.2</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>post-person</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-maven</artifactId>
                        <configuration>
                            <targetTests>
                                <param>mt.com.mongodb.starter.PersonControllerEndpointTest</param>
                            </targetTests>
                            <targetClasses>
                                <param>com.mongodb.starter.*</param>
                            </targetClasses>
                            <excludedMethods>
                                <excludedMethod>averageAge</excludedMethod>
                                <excludedMethod>count</excludedMethod>
                                <excludedMethod>delete</excludedMethod>
                                <excludedMethod>deletePerson</excludedMethod>
                                <excludedMethod>deletePersons</excludedMethod>
                                <excludedMethod>equals</excludedMethod>
                                <excludedMethod>findAll</excludedMethod>
                                <excludedMethod>findOne</excludedMethod>
                                <excludedMethod>getAverageAge</excludedMethod>
                                <excludedMethod>getCount</excludedMethod>
                                <excludedMethod>getPerson</excludedMethod>
                                <excludedMethod>getPersons</excludedMethod>
                                <excludedMethod>handleAllExceptions</excludedMethod>
                                <excludedMethod>hashCode</excludedMethod>
                                <excludedMethod>lambda$delete$2</excludedMethod>
                                <excludedMethod>lambda$deleteAll$3</excludedMethod>
                                <excludedMethod>lambda$saveAll$1</excludedMethod>
                                <excludedMethod>lambda$update$4</excludedMethod>
                                <excludedMethod>lambda$update$5</excludedMethod>
                                <excludedMethod>mapToObjectIds</excludedMethod>
                                <excludedMethod>postPersons</excludedMethod>
                                <excludedMethod>putPerson</excludedMethod>
                                <excludedMethod>toString</excludedMethod>
                                <excludedMethod>update</excludedMethod>
                            </excludedMethods>
                            <excludedClasses>
                                <excludedClass>com.mongodb.starter.dtos.AverageAgeDTO</excludedClass>
                            </excludedClasses>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
