<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>es.us.isa.httpmutator.experiment.services</groupId>
        <artifactId>mt_jdk8</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>mt-user-management</artifactId>
    <packaging>jar</packaging>

    <name>mt-user-management</name>

    <!-- <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>2.18.4</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.datatype</groupId>
                <artifactId>jackson-datatype-jsr310</artifactId>
                <version>2.18.4</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>2.18.4</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>2.18.4</version>
            </dependency>
        </dependencies>
    </dependencyManagement> -->

    <dependencies>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-models</artifactId>
            <version>1.6.16</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>mysql</artifactId>
            <version>1.19.8</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.giassi.microservice</groupId>
            <artifactId>microdemo2</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <version>2.2.4.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>org.yaml</groupId>
                    <artifactId>snakeyaml</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

    </dependencies>

    <profiles>
        <profile>
            <id>post-user</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-maven</artifactId>
                        <configuration>
                            <targetTests>
                                <param>mt.com.giassi.microservice.demo2.UserManagementEndpointTest</param>
                            </targetTests>
                            <targetClasses>
                                <param>com.giassi.microservice.demo2.*</param>
                            </targetClasses>
                            <excludedClasses>
                                <excludedClass>com.giassi.microservice.demo2.rest.GlobalExceptionHandler</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.LoginRestController</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.RBACRestController</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.RegisterRestController</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.dtos.PermissionDTO</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.dtos.RoleDTO</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.dtos.UserListDTO</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.dtos.requests.CreateOrUpdateUserDTO$CreateOrUpdateUserDTOBuilder</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.dtos.requests.LoginRequestDTO</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.dtos.requests.RegisterUserAccountDTO</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.dtos.requests.RegisterUserAccountDTO$RegisterUserAccountDTOBuilder</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.exceptions.ErrorDetails</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.services.RoleService</excludedClass>
                            </excludedClasses>
                            <excludedMethods>
                                <excludedMethod>addRole</excludedMethod>
                                <excludedMethod>builder</excludedMethod>
                                <excludedMethod>canEqual</excludedMethod>
                                <excludedMethod>deleteById</excludedMethod>
                                <excludedMethod>deleteUserById</excludedMethod>
                                <excludedMethod>equals</excludedMethod>
                                <excludedMethod>generateSalt</excludedMethod>
                                <excludedMethod>getUser</excludedMethod>
                                <excludedMethod>getUserById</excludedMethod>
                                <excludedMethod>getUserId</excludedMethod>
                                <excludedMethod>getUserList</excludedMethod>
                                <excludedMethod>getUserPresentationList</excludedMethod>
                                <excludedMethod>isPasswordValid</excludedMethod>
                                <excludedMethod>login</excludedMethod>
                                <excludedMethod>registerUserAccount</excludedMethod>
                                <excludedMethod>removeRole</excludedMethod>
                                <excludedMethod>toString</excludedMethod>
                                <excludedMethod>updateUser</excludedMethod>
                            </excludedMethods>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>put-usersId</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-maven</artifactId>
                        <configuration>
                            <targetTests>
                                <param>mt.com.giassi.microservice.demo2.UserManagementEndpointTest</param>
                            </targetTests>
                            <targetClasses>
                                <param>com.giassi.microservice.demo2.*</param>
                            </targetClasses>
                            <excludedClasses>
                                <excludedClass>com.giassi.microservice.demo2.rest.LoginRestController</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.RBACRestController</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.RegisterRestController</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.dtos.PermissionDTO</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.dtos.RoleDTO</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.dtos.UserListDTO</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.dtos.requests.CreateOrUpdateUserDTO$CreateOrUpdateUserDTOBuilder</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.dtos.requests.LoginRequestDTO</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.dtos.requests.RegisterUserAccountDTO</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.dtos.requests.RegisterUserAccountDTO$RegisterUserAccountDTOBuilder</excludedClass>
                                <excludedClass>com.giassi.microservice.demo2.rest.users.services.RoleService</excludedClass>
                            </excludedClasses>
                            <excludedMethods>
                                <excludedMethod>addContactOnUser</excludedMethod>
                                <excludedMethod>addRole</excludedMethod>
                                <excludedMethod>addUserRole</excludedMethod>
                                <excludedMethod>builder</excludedMethod>
                                <excludedMethod>canEqual</excludedMethod>
                                <excludedMethod>checkIfEmailNotUsed</excludedMethod>
                                <excludedMethod>checkIfUsernameNotUsed</excludedMethod>
                                <excludedMethod>createUser</excludedMethod>
                                <excludedMethod>deleteById</excludedMethod>
                                <excludedMethod>deleteUserById</excludedMethod>
                                <excludedMethod>generateSalt</excludedMethod>
                                <excludedMethod>getUser</excludedMethod>
                                <excludedMethod>getUserById</excludedMethod>
                                <excludedMethod>getUserId</excludedMethod>
                                <excludedMethod>getUserList</excludedMethod>
                                <excludedMethod>getUserPresentationList</excludedMethod>
                                <excludedMethod>isPasswordValid</excludedMethod>
                                <excludedMethod>login</excludedMethod>
                                <excludedMethod>registerUserAccount</excludedMethod>
                                <excludedMethod>removeRole</excludedMethod>
                                <excludedMethod>toString</excludedMethod>
                            </excludedMethods>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
