<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>es.us.isa.httpmutator.experiment.services</groupId>
        <artifactId>mt_jdk8</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <properties>
        <gson.version>2.8.9</gson.version>
    </properties>

    <artifactId>mt-genome-nexus</artifactId>
    <packaging>jar</packaging>
    <version>1.0-SNAPSHOT</version>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>${gson.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>2.2.1.RELEASE</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>2.15.2</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>2.15.2</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>2.15.2</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>3.11.2</version>
        </dependency>
        <dependency>
            <groupId>org.cbioportal.genome_nexus</groupId>
            <artifactId>web</artifactId>
            <version>1.1.49-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>io.swagger</groupId>
                    <artifactId>swagger-models</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.cbioportal.genome_nexus</groupId>
            <artifactId>service</artifactId>
            <version>1.1.49-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.cbioportal.genome_nexus</groupId>
            <artifactId>persistence</artifactId>
            <version>1.1.49-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.cbioportal.genome_nexus</groupId>
            <artifactId>component</artifactId>
            <version>1.1.49-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.cbioportal.genome_nexus</groupId>
            <artifactId>model</artifactId>
            <version>1.1.49-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>post-annotations</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-maven</artifactId>
                        <configuration>
                            <targetTests>
                                <param>mt.org.cbioportal.genome_nexus.web.GenomeNexusEndpointTest</param>
                            </targetTests>
                            <targetClasses>
                                <param>org.cbioportal.genome_nexus.*</param>
                            </targetClasses>
                            <excludedClasses>
                                <excludedClass>org.cbioportal.genome_nexus.component.annotation.EntrezGeneXrefResolver
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.component.annotation.HotspotFilter
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.component.annotation.OncokbResolver
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.component.search.SignalSearchEngine
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.AggregateSourceInfo</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.AggregatedHotspots</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.Alteration</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.Clinvar</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.CountByTumorType</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.CuriousCases</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.EnsemblCanonical</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.EnsemblGene</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.EnsemblTranscript</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.Exon</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.GeneXref</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.GeneralPopulationStats</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.Hotspot</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.HrdScore</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.Index</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.IndexSearch</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.IntergenicConsequences</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.MutationAssessor</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.MutationAssessorAnnotation
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.OncokbAnnotation</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.PdbHeader</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.PfamDomain</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.PfamDomainRange</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.PostTranslationalModification
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.ProteinLocation</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.SignalMutation</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.SignalPopulationStats</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.SignalQuery</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.SimpleCacheEntity</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.StatsByTumorType</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.UntranslatedRegion</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.Version</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.my_variant_info_model.Ann
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.my_variant_info_model.ClinVar
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.my_variant_info_model.Gene
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.my_variant_info_model.Hg38
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.my_variant_info_model.Hgvs
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.model.my_variant_info_model.Rcv
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.persistence.internal.OncokbCancerGenesListRepositoryImpl
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.persistence.internal.PdbHeaderRepositoryImpl
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.persistence.internal.PlainTextMongoRepositoryImpl
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.cached.CachedEntrezGeneXrefFetcher
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.cached.CachedVariantIdAnnotationFetcher
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.cached.CachedVariantRegionAnnotationFetcher
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.enricher.MutationAssessorAnnotationEnricher
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.enricher.OncokbAnnotationEnricher
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.exception.CuriousCasesNotFoundException
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.exception.CuriousCasesWebServiceException
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.exception.DefaultWebServiceException
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.exception.EnsemblTranscriptNotFoundException
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.exception.MutationAssessorNotFoundException
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.exception.MyVariantInfoNotFoundException
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.exception.NoEnsemblGeneIdForEntrezGeneIdException
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.exception.NoEnsemblGeneIdForHugoSymbolException
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.exception.NucleotideContextNotFoundException
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.exception.OncokbNotFoundException
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.exception.PdbHeaderNotFoundException
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.exception.PdbHeaderWebServiceException
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.exception.PfamDomainNotFoundException
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.exception.VariantAnnotationNotFoundException
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.exception.VariantAnnotationWebServiceException
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.internal.CuriousCasesServiceImpl
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.internal.GeneXrefServiceImpl
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.internal.IndexSearchServiceImpl
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.internal.InfoServiceImpl
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.internal.MutationAssessorServiceImpl
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.internal.OncokbServiceImpl
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.internal.PdbDataServiceImpl
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.internal.PfamDomainServiceImpl
                                </excludedClass>
                                <excludedClass>
                                    org.cbioportal.genome_nexus.service.internal.VerifiedGenomicLocationAnnotationServiceImpl
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.mixin.VariantAnnotationMixin
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.remote.GeneXrefDataFetcher
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.remote.MutationAssessorDataFetcher
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.remote.OncokbDataFetcher
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.remote.PdbHeaderDataFetcher
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.remote.VEPDataFetcher</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.remote.VEPIdDataFetcher
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.remote.VEPRegionDataFetcher
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.service.transformer.PdbHeaderTransformer
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.util.GenomicLocationUtil</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.util.GenomicVariant</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.util.Numerical</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.util.PdbHeaderParser</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.AnnotationSummaryController
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.CancerHotspotsController</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.CrossReferenceController</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.CuriousCasesController</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.EnsemblController</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.InfoController</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.MutationAssessorController
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.MyVariantInfoController</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.NucleotideContextController
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.PdbController</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.PfamController</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.PostTranslationalModificationController
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.SearchController</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.SignalMutationController</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.SignalQueryController</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.error.ErrorResponse</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.error.GlobalExceptionHandler
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.mixin.TranscriptConsequenceMixin
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.mixin.VariantAnnotationMixin
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.param.EnsemblFilter</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.param.PtmFilter</excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.param.SignalMutationFilter
                                </excludedClass>
                                <excludedClass>org.cbioportal.genome_nexus.web.validation.GenomicLocationValidator
                                </excludedClass>
                            </excludedClasses>
                            <excludedMethods>
                                <excludedMethod>chromosomeNormalizer</excludedMethod>
                                <excludedMethod>constructFollowUpQuery</excludedMethod>
                                <excludedMethod>createFailedAnnotation</excludedMethod>
                                <excludedMethod>enrichAnnotation</excludedMethod>
                                <excludedMethod>equals</excludedMethod>
                                <excludedMethod>extractProteinPos</excludedMethod>
                                <excludedMethod>fetchInstances</excludedMethod>
                                <excludedMethod>fetchVariantAnnotationByDbSnpIdGET</excludedMethod>
                                <excludedMethod>fetchVariantAnnotationByGenomicLocationGET</excludedMethod>
                                <excludedMethod>fetchVariantAnnotationByGenomicLocationPOST</excludedMethod>
                                <excludedMethod>fetchVariantAnnotationGET</excludedMethod>
                                <excludedMethod>fetchVariantbyDbSnpIdAnnotationPOST</excludedMethod>
                                <excludedMethod>filterHotspot</excludedMethod>
                                <excludedMethod>findHugoSymbolByEntrezGeneId</excludedMethod>
                                <excludedMethod>findOneByHugoSymbolIgnoreCase</excludedMethod>
                                <excludedMethod>findOneCanonicalByEntrezGeneId</excludedMethod>
                                <excludedMethod>findOneCanonicalByHugoSymbol</excludedMethod>
                                <excludedMethod>fromHgvs</excludedMethod>
                                <excludedMethod>fromMaf</excludedMethod>
                                <excludedMethod>fromRegion</excludedMethod>
                                <excludedMethod>generateGenomicLocation</excludedMethod>
                                <excludedMethod>generateRegion</excludedMethod>
                                <excludedMethod>genomicToEnsemblRestRegion</excludedMethod>
                                <excludedMethod>genomicToEnsemblRestRegionMap</excludedMethod>
                                <excludedMethod>genomicToHgvs</excludedMethod>
                                <excludedMethod>genomicToHgvsMap</excludedMethod>
                                <excludedMethod>getAggregateSourceInfo</excludedMethod>
                                <excludedMethod>getAltFromHgvs</excludedMethod>
                                <excludedMethod>getCanonicalEnsemblGeneIdByEntrezGeneId</excludedMethod>
                                <excludedMethod>getCanonicalEnsemblGeneIdByEntrezGeneIds</excludedMethod>
                                <excludedMethod>getCanonicalEnsemblGeneIdByHugoSymbol</excludedMethod>
                                <excludedMethod>getCanonicalEnsemblGeneIdByHugoSymbols</excludedMethod>
                                <excludedMethod>getCanonicalEnsemblTranscriptByHugoSymbol</excludedMethod>
                                <excludedMethod>getCanonicalEnsemblTranscriptsByHugoSymbols</excludedMethod>
                                <excludedMethod>getChrFromHgvs</excludedMethod>
                                <excludedMethod>getEndFromHgvs</excludedMethod>
                                <excludedMethod>getEnsemblTranscripts</excludedMethod>
                                <excludedMethod>getEnsemblTranscriptsByTranscriptId</excludedMethod>
                                <excludedMethod>getErrorPath</excludedMethod>
                                <excludedMethod>getHotspotAnnotations</excludedMethod>
                                <excludedMethod>getHotspotAnnotationsByGenomicLocation</excludedMethod>
                                <excludedMethod>getHotspotAnnotationsByGenomicLocations</excludedMethod>
                                <excludedMethod>getHotspotAnnotationsByProteinLocations</excludedMethod>
                                <excludedMethod>getHotspotAnnotationsByVariant</excludedMethod>
                                <excludedMethod>getHotspotAnnotationsByVariants</excludedMethod>
                                <excludedMethod>getHotspotsByTranscriptIds</excludedMethod>
                                <excludedMethod>getHugoSymbolByEntrezGeneId</excludedMethod>
                                <excludedMethod>getMafs</excludedMethod>
                                <excludedMethod>getNucleotideContextByVariantAnnotation</excludedMethod>
                                <excludedMethod>getOriginalInput</excludedMethod>
                                <excludedMethod>getRefFromHgvs</excludedMethod>
                                <excludedMethod>getRefTypeFromHgvs</excludedMethod>
                                <excludedMethod>getSignalMutationsByGenomicLocation</excludedMethod>
                                <excludedMethod>getSignalMutationsByHgvsg</excludedMethod>
                                <excludedMethod>getStartFromHgvs</excludedMethod>
                                <excludedMethod>getTransformer</excludedMethod>
                                <excludedMethod>getTypeFromHgvs</excludedMethod>
                                <excludedMethod>getVariantAnnotation</excludedMethod>
                                <excludedMethod>getVariantAnnotationExternally</excludedMethod>
                                <excludedMethod>getVariantFormat</excludedMethod>
                                <excludedMethod>hashCode</excludedMethod>
                                <excludedMethod>hgvsgToGenomicLocation</excludedMethod>
                                <excludedMethod>hgvsgToGenomicLocations</excludedMethod>
                                <excludedMethod>initHugoSymbolToEntrezGeneIdMap</excludedMethod>
                                <excludedMethod>isHgvsFormat</excludedMethod>
                                <excludedMethod>isMafFile</excludedMethod>
                                <excludedMethod>isRegion</excludedMethod>
                                <excludedMethod>lambda$buildQueryIndex$0</excludedMethod>
                                <excludedMethod>lambda$findCanonicalTranscriptIdsBySource$0</excludedMethod>
                                <excludedMethod>lambda$genomicLocationToVariant$1</excludedMethod>
                                <excludedMethod>lambda$genomicLocationToVariant$2</excludedMethod>
                                <excludedMethod>lambda$genomicLocationToVariant$3</excludedMethod>
                                <excludedMethod>lambda$getAnnotations$0</excludedMethod>
                                <excludedMethod>lambda$getAnnotations$1</excludedMethod>
                                <excludedMethod>lambda$getVariantAnnotationExternally$0</excludedMethod>
                                <excludedMethod>lambda$getVariantAnnotationExternally$1</excludedMethod>
                                <excludedMethod>lambda$mapConvertedVarsToOrigVarQuery$3</excludedMethod>
                                <excludedMethod>lambda$null$2</excludedMethod>
                                <excludedMethod>lambda$queryToVariant$1</excludedMethod>
                                <excludedMethod>lambda$variantToProteinChange$4</excludedMethod>
                                <excludedMethod>longestCommonPrefix</excludedMethod>
                                <excludedMethod>mapConvertedVarsToOrigVarQuery</excludedMethod>
                                <excludedMethod>mapMutationToExactQuery</excludedMethod>
                                <excludedMethod>normalizeAlteration</excludedMethod>
                                <excludedMethod>normalizeGenomicLocation</excludedMethod>
                                <excludedMethod>parseGenomicLocation</excludedMethod>
                                <excludedMethod>postVariantAnnotation</excludedMethod>
                                <excludedMethod>resolveHgvspShortFromAAs</excludedMethod>
                                <excludedMethod>sameLengthUnknownNucleotideString</excludedMethod>
                                <excludedMethod>search</excludedMethod>
                                <excludedMethod>toRegion</excludedMethod>
                                <excludedMethod>toString</excludedMethod>
                                <excludedMethod>unregisterEnricher</excludedMethod>
                            </excludedMethods>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>