<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>es.us.isa.httpmutator.experiment.services</groupId>
        <artifactId>mt_jdk11</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>mt-project-tracking-system</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.4.7</version>   
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-core</artifactId>
                <version>1.6.16</version>
            </dependency>
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-models</artifactId>
                <version>1.6.16</version>
            </dependency>
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-parser</artifactId>
                <version>1.0.75</version>
            </dependency>
            <dependency>
                <groupId>io.swagger.parser.v3</groupId>
                <artifactId>swagger-parser</artifactId>
                <version>2.1.22</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.pfa</groupId>
            <artifactId>project-tracking-system</artifactId>
            <version>9.0</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>


    <profiles>
        <profile>
            <id>post-employees</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-maven</artifactId>
                        <configuration>
                            <targetTests>
                                <param>mt.com.pfa.ProjectTrackingSystemEndpointTest</param>
                            </targetTests>
                            <targetClasses>
                                <param>com.pfa.pack.*</param>
                            </targetClasses>
                            <excludedClasses>
                                <excludedClass>com.pfa.pack.controller.api.AssignmentResource</excludedClass>
                                <excludedClass>com.pfa.pack.controller.api.AuthenticationResource</excludedClass>
                                <excludedClass>com.pfa.pack.controller.api.CredentialResource</excludedClass>
                                <excludedClass>com.pfa.pack.controller.api.DepartmentResource</excludedClass>
                                <excludedClass>com.pfa.pack.controller.api.LocationResource</excludedClass>
                                <excludedClass>com.pfa.pack.controller.api.ProjectResource</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.CredentialController</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.ErrorAppController</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.HomeController</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.admin.AdminController</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.admin.AdminDepartmentController</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.admin.AdminEmployeeController</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.admin.AdminLocationController</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.employee.EmployeeController</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.manager.ManagerController</excludedClass>
                                <excludedClass>com.pfa.pack.converter.EmployeeAssignedProjectConverter</excludedClass>
                                <excludedClass>com.pfa.pack.converter.EmployeeDtoToEmployeeConverter</excludedClass>
                                <excludedClass>com.pfa.pack.converter.ProjectDtoProjectConverter</excludedClass>
                                <excludedClass>com.pfa.pack.converter.ProjectProjectDtoConverter</excludedClass>
                                <excludedClass>com.pfa.pack.exception.ExceptionMsgApiHandler</excludedClass>
                                <excludedClass>com.pfa.pack.exception.ExceptionMsgHandler</excludedClass>
                                <excludedClass>com.pfa.pack.exception.payload.ExceptionMsg</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.AssignEmployeesDto</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.AssignmentDto</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.AuthenticationRequest</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.AuthenticationResponse</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.EmployeeAssignedProjectDto</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.EmployeeDto</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.ProjectDTO</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.SearchProjectsDto</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.collection.DtoCollection</excludedClass>
                                <excludedClass>com.pfa.pack.model.entity.Assignment</excludedClass>
                                <excludedClass>com.pfa.pack.model.entity.Project</excludedClass>
                                <excludedClass>com.pfa.pack.model.id.AssignmentId</excludedClass>
                                <excludedClass>com.pfa.pack.security.UserDetailsImpl</excludedClass>
                                <excludedClass>com.pfa.pack.security.UserDetailsServiceImpl</excludedClass>
                                <excludedClass>com.pfa.pack.service.impl.AssignmentServiceImpl</excludedClass>
                                <excludedClass>com.pfa.pack.service.impl.AuthenticationServiceImpl</excludedClass>
                                <excludedClass>com.pfa.pack.service.impl.CredentialServiceImpl</excludedClass>
                                <excludedClass>com.pfa.pack.service.impl.DepartmentServiceImpl</excludedClass>
                                <excludedClass>com.pfa.pack.service.impl.LocationServiceImpl</excludedClass>
                                <excludedClass>com.pfa.pack.service.impl.ProjectServiceImpl</excludedClass>
                                <excludedClass>com.pfa.pack.util.email.EmailUtilImpl</excludedClass>
                                <excludedClass>com.pfa.pack.util.sms.Sms</excludedClass>
                                <excludedClass>com.pfa.pack.util.sms.SmsUtilImpl</excludedClass>
                                <excludedClass>mt.dhl.Main</excludedClass>
                            </excludedClasses>

                            <excludedMethods>
                                <excludedMethod>deleteById</excludedMethod>
                                <excludedMethod>deleteByUsername</excludedMethod>
                                <excludedMethod>findAll</excludedMethod>
                                <excludedMethod>findAllManagers</excludedMethod>
                                <excludedMethod>findByDepartmentId</excludedMethod>
                                <excludedMethod>findByEmployeeProjectDataEmployeeId</excludedMethod>
                                <excludedMethod>findById</excludedMethod>
                                <excludedMethod>findByManagerId</excludedMethod>
                                <excludedMethod>findByManagerIdAndProjectId</excludedMethod>
                                <excludedMethod>findByUsername</excludedMethod>
                                <excludedMethod>findManagerProjectDataByEmployeeId</excludedMethod>
                                <excludedMethod>getAssignments</excludedMethod>
                                <excludedMethod>getDepartments</excludedMethod>
                                <excludedMethod>getEmployee</excludedMethod>
                                <excludedMethod>getEmployees</excludedMethod>
                                <excludedMethod>getTrialNumber</excludedMethod>
                                <excludedMethod>lambda$findById$0</excludedMethod>
                                <excludedMethod>update</excludedMethod>
                            </excludedMethods>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>post-assignments</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-maven</artifactId>
                        <configuration>
                            <targetTests>
                                <param>mt.com.pfa.ProjectTrackingSystemEndpointTest</param>
                            </targetTests>
                            <targetClasses>
                                <param>com.pfa.pack.*</param>
                            </targetClasses>
                            <excludedClasses>
                                <excludedClass>com.pfa.pack.controller.api.AuthenticationResource</excludedClass>
                                <excludedClass>com.pfa.pack.controller.api.CredentialResource</excludedClass>
                                <excludedClass>com.pfa.pack.controller.api.DepartmentResource</excludedClass>
                                <excludedClass>com.pfa.pack.controller.api.EmployeeResource</excludedClass>
                                <excludedClass>com.pfa.pack.controller.api.LocationResource</excludedClass>
                                <excludedClass>com.pfa.pack.controller.api.ProjectResource</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.CredentialController</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.ErrorAppController</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.HomeController</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.admin.AdminController</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.admin.AdminDepartmentController</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.admin.AdminEmployeeController</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.admin.AdminLocationController</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.employee.EmployeeController</excludedClass>
                                <excludedClass>com.pfa.pack.controller.business.manager.ManagerController</excludedClass>
                                <excludedClass>com.pfa.pack.converter.EmployeeAssignedProjectConverter</excludedClass>
                                <excludedClass>com.pfa.pack.converter.EmployeeDtoToEmployeeConverter</excludedClass>
                                <excludedClass>com.pfa.pack.converter.ProjectDtoProjectConverter</excludedClass>
                                <excludedClass>com.pfa.pack.converter.ProjectProjectDtoConverter</excludedClass>
                                <excludedClass>com.pfa.pack.exception.ExceptionMsgApiHandler</excludedClass>
                                <excludedClass>com.pfa.pack.exception.ExceptionMsgHandler</excludedClass>
                                <excludedClass>com.pfa.pack.exception.payload.ExceptionMsg</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.AssignEmployeesDto</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.AssignmentDto</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.AuthenticationRequest</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.AuthenticationResponse</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.EmployeeAssignedProjectDto</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.EmployeeDto</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.ProjectDTO</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.SearchProjectsDto</excludedClass>
                                <excludedClass>com.pfa.pack.model.dto.collection.DtoCollection</excludedClass>
                                <excludedClass>com.pfa.pack.model.id.AssignmentId</excludedClass>
                                <excludedClass>com.pfa.pack.security.UserDetailsImpl</excludedClass>
                                <excludedClass>com.pfa.pack.security.UserDetailsServiceImpl</excludedClass>
                                <excludedClass>com.pfa.pack.service.impl.AuthenticationServiceImpl</excludedClass>
                                <excludedClass>com.pfa.pack.service.impl.CredentialServiceImpl</excludedClass>
                                <excludedClass>com.pfa.pack.service.impl.DepartmentServiceImpl</excludedClass>
                                <excludedClass>com.pfa.pack.service.impl.EmployeeServiceImpl</excludedClass>
                                <excludedClass>com.pfa.pack.service.impl.LocationServiceImpl</excludedClass>
                                <excludedClass>com.pfa.pack.service.impl.ProjectServiceImpl</excludedClass>
                                <excludedClass>com.pfa.pack.util.email.EmailUtilImpl</excludedClass>
                                <excludedClass>com.pfa.pack.util.sms.Sms</excludedClass>
                                <excludedClass>com.pfa.pack.util.sms.SmsUtilImpl</excludedClass>
                                <excludedClass>mt.dhl.Main</excludedClass>
                            </excludedClasses>
                            <excludedMethods>
                                <excludedMethod>deleteById</excludedMethod>
                                <excludedMethod>deleteByProjectId</excludedMethod>
                                <excludedMethod>findAll</excludedMethod>
                                <excludedMethod>findAllByEmployeeIdAndManagerId</excludedMethod>
                                <excludedMethod>findByEmployeeId</excludedMethod>
                                <excludedMethod>findByEmployeeIdAndProjectId</excludedMethod>
                                <excludedMethod>findByEmployeeIdAndProjectIdAndCommitDate</excludedMethod>
                                <excludedMethod>findById</excludedMethod>
                                <excludedMethod>findByProjectId</excludedMethod>
                                <excludedMethod>findByProjectIdAndCommitDateFromAndCommitDateTo</excludedMethod>
                                <excludedMethod>getAssignments</excludedMethod>
                                <excludedMethod>getDepartments</excludedMethod>
                                <excludedMethod>getEmployees</excludedMethod>
                                <excludedMethod>getTrialNumber</excludedMethod>
                                <excludedMethod>lambda$findByEmployeeIdAndProjectIdAndCommitDate$1</excludedMethod>
                                <excludedMethod>lambda$findById$0</excludedMethod>
                                <excludedMethod>update</excludedMethod>
                            </excludedMethods>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>