<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>es.us.isa.httpmutator.experiment.services</groupId>
        <artifactId>mt_jdk8</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>mt-proxyprint</artifactId>
    <packaging>jar</packaging>

    <name>mt-proxyprint</name>
    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-core</artifactId>
                <version>1.6.16</version>
            </dependency>
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-models</artifactId>
                <version>1.6.16</version>
            </dependency>
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-parser</artifactId>
                <version>1.0.75</version>
            </dependency>

            <dependency>
                <groupId>com.fasterxml.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>2.13.5</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>


    <dependencies>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-parser</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-models</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Jackson 三件套（由 BOM 管版本） -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.proxyprint</groupId>
            <artifactId>ProxyPrint-kitchen</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <version>1.4.4.RELEASE</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>post-request-register</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-maven</artifactId>
                        <configuration>
                            <targetTests>
                                <param>mt.io.github.proxyprint.kitchen.ProxyprintEndpointTest</param>
                            </targetTests>
                            <targetClasses>
                                <param>io.github.proxyprint.kitchen.*</param>
                            </targetClasses>
                            <excludedClasses>
                                <excludedClass>io.github.proxyprint.kitchen.Configuration</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.config.NgrokConfig</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.DefaultController</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.admin.AdminController</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.consumer.ConsumerController</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.consumer.PayPalController</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.consumer.PrintRequestController</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.consumer.PrintingSchemaController</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.consumer.printrequest.ConsumerPrintRequest</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.consumer.printrequest.ConsumerPrintRequestDocumentInfo</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.notifications.NotificationsController</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.printshops.EmployeeController</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.printshops.ManagerController</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.printshops.PriceTableController</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.printshops.PrintShopController</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.printshops.ReviewController</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.printshops.pricetable.CoverTableItem</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.printshops.pricetable.CoversTable</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.printshops.pricetable.PaperTableItem</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.printshops.pricetable.PapersTable</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.printshops.pricetable.RingTableItem</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.controllers.printshops.pricetable.RingsTable</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.Money</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.User</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.consumer.PrintingSchema</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.consumer.printrequest.Document</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.consumer.printrequest.DocumentSpec</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.consumer.printrequest.PrintRequest</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.notifications.Notification</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.printshops.PrintShop</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.printshops.RegisterRequestDateComparator</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.printshops.Review</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.printshops.pricetable.BindingItem</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.printshops.pricetable.BudgetCalculator</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.printshops.pricetable.CoverItem</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.printshops.pricetable.Item</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.printshops.pricetable.ItemFactory</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.printshops.pricetable.PaperItem</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.printshops.pricetable.RangePaperItem</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.models.repositories.UserService</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.utils.DeleteTask</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.utils.DistanceCalculator</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.utils.MailBox</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.utils.MailBox$1</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.utils.MailBox$2</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.utils.MailBox$3</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.utils.MailBox$4</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.utils.NotificationManager</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.utils.PayPalWrapper</excludedClass>
                                <excludedClass>io.github.proxyprint.kitchen.utils.gson.AnnotationExclusionStrategy</excludedClass>
                            </excludedClasses>
                            <excludedMethods>
                                <excludedMethod>acceptRequest</excludedMethod>
                                <excludedMethod>addPrintingSchema</excludedMethod>
                                <excludedMethod>configure</excludedMethod>
                                <excludedMethod>deletePrintingSchema</excludedMethod>
                                <excludedMethod>equals</excludedMethod>
                                <excludedMethod>getBalance</excludedMethod>
                                <excludedMethod>getEmail</excludedMethod>
                                <excludedMethod>getLatitude</excludedMethod>
                                <excludedMethod>getLongitude</excludedMethod>
                                <excludedMethod>getName</excludedMethod>
                                <excludedMethod>getNotifications</excludedMethod>
                                <excludedMethod>getPrintRequests</excludedMethod>
                                <excludedMethod>getPrintShop</excludedMethod>
                                <excludedMethod>getPrintingSchemas</excludedMethod>
                                <excludedMethod>hashCode</excludedMethod>
                                <excludedMethod>isAccepted</excludedMethod>
                                <excludedMethod>readAllNotifications</excludedMethod>
                                <excludedMethod>rejectRequest</excludedMethod>
                                <excludedMethod>removeAllNotifications</excludedMethod>
                                <excludedMethod>toString</excludedMethod>
                            </excludedMethods>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
