openapi: 3.0.1
info:
  title: Api Documentation
  description: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: "1.0"
servers:
- url: http://localhost:50115/
tags:
- name: basic-error-controller
  description: Basic Error Controller
- name: login-rest-controller
  description: Login Rest Controller
- name: rbac-rest-controller
  description: RBAC Rest Controller
- name: register-rest-controller
  description: Register Rest Controller
- name: user-rest-controller
  description: User Rest Controller
paths:
  /users:
    post:
      tags:
      - user-rest-controller
      summary: createUser
      operationId: createUserUsingPOST
      requestBody:
        description: createOrUpdateUserDTO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrUpdateUserDTO'
        required: true
      responses:
        201:
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserDTO'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    message:
                        type: string
                    timestamp:
                        type: string
                    status:
                        type: integer
                    error:
                        type: string
                    path:
                        type: string
      deprecated: false
      x-codegen-request-body-name: createOrUpdateUserDTO
components:
  schemas:
    AddressDTO:
      title: AddressDTO
      type: object
      properties:
        address:
          type: string
          x-nullable: true
          nullable: true
        address2:
          type: string
          x-nullable: true
          nullable: true
        city:
          type: string
          x-nullable: true
          nullable: true
        country:
          type: string
          x-nullable: true
          nullable: true
        zipCode:
          type: string
          x-nullable: true
          nullable: true
    ContactDTO:
      title: ContactDTO
      type: object
      properties:
        contactNote:
          type: string
          x-nullable: true
          nullable: true
        email:
          type: string
        facebook:
          type: string
          x-nullable: true
          nullable: true
        linkedin:
          type: string
          x-nullable: true
          nullable: true
        phone:
          type: string
          x-nullable: true
          nullable: true
        skype:
          type: string
          x-nullable: true
          nullable: true
        website:
          type: string
          x-nullable: true
          nullable: true
    CreateOrUpdateUserDTO:
      title: CreateOrUpdateUserDTO
      type: object
      properties:
        address:
          type: string
        address2:
          type: string
        birthDate:
          type: string
          format: date
        city:
          type: string
        contactNote:
          type: string
        country:
          type: string
        email:
          type: string
        enabled:
          type: boolean
        facebook:
          type: string
        gender:
          type: string
        linkedin:
          type: string
        mobile:
          type: string
        name:
          type: string
        note:
          type: string
        password:
          type: string
        secured:
          type: boolean
        skype:
          type: string
        surname:
          type: string
        username:
          type: string
        website:
          type: string
        zipCode:
          type: string
    LoginRequestDTO:
      title: LoginRequestDTO
      type: object
      properties:
        password:
          type: string
        username:
          type: string
    ModelAndView:
      title: ModelAndView
      type: object
      properties:
        empty:
          type: boolean
        model:
          type: object
          properties: {}
        modelMap:
          type: object
          additionalProperties:
            type: object
            properties: {}
        reference:
          type: boolean
        status:
          type: string
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
        view:
          $ref: '#/components/schemas/View'
        viewName:
          type: string
    PermissionDTO:
      title: PermissionDTO
      type: object
      properties:
        id:
          type: integer
          format: int64
        permission:
          type: string
    RegisterUserAccountDTO:
      title: RegisterUserAccountDTO
      type: object
      properties:
        email:
          type: string
        gender:
          type: string
        name:
          type: string
        password:
          type: string
        surname:
          type: string
        username:
          type: string
    RoleDTO:
      title: RoleDTO
      type: object
      properties:
        id:
          type: integer
          format: int64
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/PermissionDTO'
        role:
          type: string
    UserDTO:
      title: UserDTO
      type: object
      properties:
        addressDTO:
          $ref: '#/components/schemas/AddressDTO'
        birthDate:
          type: string
          format: date
          x-nullable: true
          nullable: true
        contactDTO:
          $ref: '#/components/schemas/ContactDTO'
        creationDt:
          type: string
          pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?$
        enabled:
          type: boolean
        gender:
          type: string
        id:
          type: integer
          format: int64
        loginDt:
          type: string
          format: date-time
          x-nullable: true
          nullable: true
        name:
          type: string
        note:
          type: string
          x-nullable: true
          nullable: true
        permissions:
          type: array
          items:
            type: string
        roles:
          type: array
          items:
            type: string
        secured:
          type: boolean
        surname:
          type: string
          x-nullable: true
          nullable: true
        updatedDt:
          type: string
          format: date-time
          x-nullable: true
          nullable: true
        username:
          type: string
    UserListDTO:
      title: UserListDTO
      type: object
      properties:
        userList:
          type: array
          items:
            $ref: '#/components/schemas/UserDTO'
    View:
      title: View
      type: object
      properties:
        contentType:
          type: string
