<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>es.us.isa.httpmutator.experiment.services</groupId>
        <artifactId>mt_jdk8</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>mt-scout-api</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>se.devscout</groupId>
            <artifactId>api</artifactId>
            <version>1.0-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava-jdk5</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>se.devscout</groupId>
            <artifactId>data-access</artifactId>
            <version>1.0-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava-jdk5</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>se.devscout</groupId>
            <artifactId>auth</artifactId>
            <version>1.0-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava-jdk5</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>se.devscout</groupId>
            <artifactId>data-batch-jobs</artifactId>
            <version>1.0-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava-jdk5</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.fasterxml.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>2.15.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>33.3.1-jre</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>org.yaml</groupId>
                <artifactId>snakeyaml</artifactId>
                <version>1.33</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <profiles>
        <profile>
            <id>post-activities</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-maven</artifactId>
                        <configuration>
                            <targetTests>
                                <param>mt.se.devscout.scoutapi.ScoutAPIEndpointTest</param>
                            </targetTests>
                            <targetClasses>
                                <param>se.devscout.scoutapi.*</param>
                            </targetClasses>
                            <excludedClasses>
                                <excludedClass>se.devscout.scoutapi.ConfigurationHealthCheck</excludedClass>
                                <excludedClass>se.devscout.scoutapi.ScoutAPIApplication$2</excludedClass>
                                <excludedClass>se.devscout.scoutapi.activityimporter.ActivitiesImporter</excludedClass>
                                <excludedClass>se.devscout.scoutapi.activityimporter.ActivitiesImporter$Task
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.activityimporter.AktivitetsbankenCrawler
                                </excludedClass>
                                <excludedClass>
                                    se.devscout.scoutapi.activityimporter.AktivitetsbankenCrawler$AgeInterval
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.activityimporter.DefaultWebPageLoader
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.auth.Role</excludedClass>
                                <excludedClass>se.devscout.scoutapi.auth.google.Checker</excludedClass>
                                <excludedClass>se.devscout.scoutapi.auth.google.Configuration</excludedClass>
                                <excludedClass>se.devscout.scoutapi.auth.google.GoogleAuthenticator</excludedClass>
                                <excludedClass>se.devscout.scoutapi.auth.google.Verify</excludedClass>
                                <excludedClass>se.devscout.scoutapi.auth.google.Verify$TokenStatus</excludedClass>
                                <excludedClass>se.devscout.scoutapi.auth.google.Verify$VerificationResponse
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.dao.ActivityRatingDao</excludedClass>
                                <excludedClass>se.devscout.scoutapi.dao.DataAccessUtils</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityDerived</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityPropertiesTag$Key</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityRating</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityRating$Key</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityRatingAttrs</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityRelation</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityRelation$Key</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.SystemMessage</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.ActivityResourceV2</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.SystemMessageResource</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.SystemResource</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.SystemResource$RolesView</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.TagResource</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.UserProfileView</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.UserResource</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.UserView</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.v1.ActivityApiV1View</excludedClass>
                                <excludedClass>
                                    se.devscout.scoutapi.resource.v1.ActivityApiV1View$RelatedActivityIdView
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.v1.CategoryResource</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.v1.FavouritesResourceV1</excludedClass>
                                <excludedClass>
                                    se.devscout.scoutapi.resource.v1.FavouritesResourceV1$PutFavouritesEntity
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.ActivityMetadata</excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.Configuration</excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.RelatedActivitiesUpdater
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.WordHistogram</excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.AbstractRangeComparator
                                </excludedClass>
                                <excludedClass>
                                    se.devscout.scoutapi.textanalyzer.comparator.AbstractWordsHistogramComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.AgeComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.AllTextComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.CategoryComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.IntroductionTextComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.MaterialTextComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.NameTextComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.ParticipantCountComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.TimeComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.report.Report$Entity</excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.report.StringMapXmlAdapter
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.simplify.Simplifier</excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.simplify.SimplifyRule</excludedClass>
                                <excludedClass>se.devscout.scoutapi.util.MediaFileUtils</excludedClass>
                                <excludedClass>se.devscout.scoutapi.util.MediaFileUtils$AutoAssignMediaFileToTags
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.util.MediaFileUtils$CleanResizedImagesCacheTask
                                </excludedClass>
                            </excludedClasses>
                            <excludedMethods>
                                <excludedMethod>byKeyword</excludedMethod>
                                <excludedMethod>createFromMultiPart</excludedMethod>
                                <excludedMethod>createTransaction</excludedMethod>
                                <excludedMethod>delete</excludedMethod>
                                <excludedMethod>deleteRating</excludedMethod>
                                <excludedMethod>downloadFile</excludedMethod>
                                <excludedMethod>equals</excludedMethod>
                                <excludedMethod>get</excludedMethod>
                                <excludedMethod>getActivities</excludedMethod>
                                <excludedMethod>getActivity</excludedMethod>
                                <excludedMethod>getActivityProperties</excludedMethod>
                                <excludedMethod>getActivityPropertiesId</excludedMethod>
                                <excludedMethod>getConnection</excludedMethod>
                                <excludedMethod>getDerived</excludedMethod>
                                <excludedMethod>getEmailAddress</excludedMethod>
                                <excludedMethod>getIdentityById</excludedMethod>
                                <excludedMethod>getKeywords</excludedMethod>
                                <excludedMethod>getLevel</excludedMethod>
                                <excludedMethod>getLocalFileName</excludedMethod>
                                <excludedMethod>getLocalFileURL</excludedMethod>
                                <excludedMethod>getMediaFileId</excludedMethod>
                                <excludedMethod>getPublishingActivity</excludedMethod>
                                <excludedMethod>getRating</excludedMethod>
                                <excludedMethod>getRelated</excludedMethod>
                                <excludedMethod>getRelatedActivityIds</excludedMethod>
                                <excludedMethod>getRelations</excludedMethod>
                                <excludedMethod>getSimilarityCalculatorConfiguration</excludedMethod>
                                <excludedMethod>getSimplifiedKeyword</excludedMethod>
                                <excludedMethod>getTagList</excludedMethod>
                                <excludedMethod>isApiKeySet</excludedMethod>
                                <excludedMethod>isContentEqual</excludedMethod>
                                <excludedMethod>isUsed</excludedMethod>
                                <excludedMethod>lambda$all$0</excludedMethod>
                                <excludedMethod>lambda$all$2</excludedMethod>
                                <excludedMethod>lambda$createFromMultiPart$0</excludedMethod>
                                <excludedMethod>lambda$getMediaFiles$5</excludedMethod>
                                <excludedMethod>lambda$getRelated$0</excludedMethod>
                                <excludedMethod>lambda$getRelatedIds$1</excludedMethod>
                                <excludedMethod>lambda$getRelatedIds$2</excludedMethod>
                                <excludedMethod>lambda$getTagList$4</excludedMethod>
                                <excludedMethod>lambda$initActivityUpdater$1</excludedMethod>
                                <excludedMethod>lambda$initSystemMessages$3</excludedMethod>
                                <excludedMethod>lambda$initSystemMessages$4</excludedMethod>
                                <excludedMethod>lambda$null$1</excludedMethod>
                                <excludedMethod>lambda$setActivityRelations$9</excludedMethod>
                                <excludedMethod>main</excludedMethod>
                                <excludedMethod>okResponse</excludedMethod>
                                <excludedMethod>patch</excludedMethod>
                                <excludedMethod>postRating</excludedMethod>
                                <excludedMethod>readUser</excludedMethod>
                                <excludedMethod>saveBodyPartAsFile</excludedMethod>
                                <excludedMethod>saveDataUriAsFile</excludedMethod>
                                <excludedMethod>setActivityRelations</excludedMethod>
                                <excludedMethod>setFavouritesCount</excludedMethod>
                                <excludedMethod>setRatingsCount</excludedMethod>
                                <excludedMethod>setRatingsSum</excludedMethod>
                                <excludedMethod>toJson</excludedMethod>
                                <excludedMethod>toString</excludedMethod>
                                <excludedMethod>unsetPublishedProperties</excludedMethod>
                                <excludedMethod>update</excludedMethod>
                                <excludedMethod>updateProperties</excludedMethod>
                            </excludedMethods>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>post-users</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-maven</artifactId>
                        <configuration>
                            <targetTests>
                                <param>mt.se.devscout.scoutapi.ScoutAPIEndpointTest</param>
                            </targetTests>
                            <targetClasses>
                                <param>se.devscout.scoutapi.*</param>
                            </targetClasses>
                            <excludedClasses>
                                <excludedClass>se.devscout.scoutapi.ConfigurationHealthCheck</excludedClass>
                                <excludedClass>se.devscout.scoutapi.ScoutAPIApplication$2</excludedClass>
                                <excludedClass>se.devscout.scoutapi.activityimporter.ActivitiesImporter</excludedClass>
                                <excludedClass>se.devscout.scoutapi.activityimporter.ActivitiesImporter$Task</excludedClass>
                                <excludedClass>se.devscout.scoutapi.activityimporter.AktivitetsbankenCrawler
                                </excludedClass>
                                <excludedClass>
                                    se.devscout.scoutapi.activityimporter.AktivitetsbankenCrawler$AgeInterval
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.activityimporter.DefaultWebPageLoader
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.auth.Role</excludedClass>
                                <excludedClass>se.devscout.scoutapi.auth.google.Checker</excludedClass>
                                <excludedClass>se.devscout.scoutapi.auth.google.Configuration</excludedClass>
                                <excludedClass>se.devscout.scoutapi.auth.google.GoogleAuthenticator</excludedClass>
                                <excludedClass>se.devscout.scoutapi.auth.google.Verify</excludedClass>
                                <excludedClass>se.devscout.scoutapi.auth.google.Verify$TokenStatus</excludedClass>
                                <excludedClass>se.devscout.scoutapi.auth.google.Verify$VerificationResponse
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.dao.ActivityDao</excludedClass>
                                <excludedClass>se.devscout.scoutapi.dao.ActivityRatingDao</excludedClass>
                                <excludedClass>se.devscout.scoutapi.dao.DataAccessUtils</excludedClass>
                                <excludedClass>se.devscout.scoutapi.dao.MediaFileDao</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityDerived</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityPropertiesMediaFile</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityPropertiesMediaFile$Key
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityPropertiesTag</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityPropertiesTag$Key</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityRating</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityRating$Key</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityRatingAttrs</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityRelation</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.ActivityRelation$Key</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.MediaFile</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.SystemMessage</excludedClass>
                                <excludedClass>se.devscout.scoutapi.model.TagDerived</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.ActivityResource</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.ActivityResourceV2</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.SystemMessageResource</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.SystemResource</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.SystemResource$RolesView</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.TagResource</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.UserProfileView</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.UserView</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.v1.ActivityApiV1View</excludedClass>
                                <excludedClass>
                                    se.devscout.scoutapi.resource.v1.ActivityApiV1View$RelatedActivityIdView
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.v1.ActivityResourceV1</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.v1.CategoryResource</excludedClass>
                                <excludedClass>se.devscout.scoutapi.resource.v1.FavouritesResourceV1</excludedClass>
                                <excludedClass>
                                    se.devscout.scoutapi.resource.v1.FavouritesResourceV1$PutFavouritesEntity
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.ActivityMetadata</excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.Configuration</excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.RelatedActivitiesUpdater
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.WordHistogram</excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.AbstractRangeComparator
                                </excludedClass>
                                <excludedClass>
                                    se.devscout.scoutapi.textanalyzer.comparator.AbstractWordsHistogramComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.AgeComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.AllTextComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.CategoryComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.IntroductionTextComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.MaterialTextComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.NameTextComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.ParticipantCountComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.comparator.TimeComparator
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.report.Report$Entity</excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.report.StringMapXmlAdapter
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.simplify.Simplifier</excludedClass>
                                <excludedClass>se.devscout.scoutapi.textanalyzer.simplify.SimplifyRule</excludedClass>
                                <excludedClass>se.devscout.scoutapi.util.MediaFileUtils</excludedClass>
                                <excludedClass>se.devscout.scoutapi.util.MediaFileUtils$AutoAssignMediaFileToTags
                                </excludedClass>
                                <excludedClass>se.devscout.scoutapi.util.MediaFileUtils$CleanResizedImagesCacheTask
                                </excludedClass>
                            </excludedClasses>
                            <excludedMethods>
                                <excludedMethod>createFromMultiPart</excludedMethod>
                                <excludedMethod>createTransaction</excludedMethod>
                                <excludedMethod>delete</excludedMethod>
                                <excludedMethod>downloadFile</excludedMethod>
                                <excludedMethod>equals</excludedMethod>
                                <excludedMethod>get</excludedMethod>
                                <excludedMethod>getActivitiesCount</excludedMethod>
                                <excludedMethod>getActivity</excludedMethod>
                                <excludedMethod>getAgeMax</excludedMethod>
                                <excludedMethod>getAgeMin</excludedMethod>
                                <excludedMethod>getAuthor</excludedMethod>
                                <excludedMethod>getConnection</excludedMethod>
                                <excludedMethod>getDateCreated</excludedMethod>
                                <excludedMethod>getDatePublished</excludedMethod>
                                <excludedMethod>getDateUpdated</excludedMethod>
                                <excludedMethod>getDerived</excludedMethod>
                                <excludedMethod>getDescriptionIntroduction</excludedMethod>
                                <excludedMethod>getDescriptionMain</excludedMethod>
                                <excludedMethod>getDescriptionMaterial</excludedMethod>
                                <excludedMethod>getDescriptionNotes</excludedMethod>
                                <excludedMethod>getDescriptionPrepare</excludedMethod>
                                <excludedMethod>getDescriptionSafety</excludedMethod>
                                <excludedMethod>getFavouritesCount</excludedMethod>
                                <excludedMethod>getIdentityById</excludedMethod>
                                <excludedMethod>getLevel</excludedMethod>
                                <excludedMethod>getLocalFileName</excludedMethod>
                                <excludedMethod>getLocalFileURL</excludedMethod>
                                <excludedMethod>getMediaFile</excludedMethod>
                                <excludedMethod>getMediaFiles</excludedMethod>
                                <excludedMethod>getParticipantsMax</excludedMethod>
                                <excludedMethod>getParticipantsMin</excludedMethod>
                                <excludedMethod>getProperties</excludedMethod>
                                <excludedMethod>getPropertiesRevisions</excludedMethod>
                                <excludedMethod>getPublishingActivity</excludedMethod>
                                <excludedMethod>getRatingsAverage</excludedMethod>
                                <excludedMethod>getRatingsCount</excludedMethod>
                                <excludedMethod>getRatingsSum</excludedMethod>
                                <excludedMethod>getRelated</excludedMethod>
                                <excludedMethod>getRelatedIds</excludedMethod>
                                <excludedMethod>getRelations</excludedMethod>
                                <excludedMethod>getSimilarityCalculatorConfiguration</excludedMethod>
                                <excludedMethod>getSource</excludedMethod>
                                <excludedMethod>getTagList</excludedMethod>
                                <excludedMethod>getTags</excludedMethod>
                                <excludedMethod>getTimeMax</excludedMethod>
                                <excludedMethod>getTimeMin</excludedMethod>
                                <excludedMethod>hashCode</excludedMethod>
                                <excludedMethod>isApiKeySet</excludedMethod>
                                <excludedMethod>isContentEqual</excludedMethod>
                                <excludedMethod>isFeatured</excludedMethod>
                                <excludedMethod>lambda$createFromMultiPart$0</excludedMethod>
                                <excludedMethod>lambda$getMediaFiles$2</excludedMethod>
                                <excludedMethod>lambda$getMediaFiles$5</excludedMethod>
                                <excludedMethod>lambda$getRelated$0</excludedMethod>
                                <excludedMethod>lambda$getRelatedIds$1</excludedMethod>
                                <excludedMethod>lambda$getRelatedIds$2</excludedMethod>
                                <excludedMethod>lambda$getTagList$4</excludedMethod>
                                <excludedMethod>lambda$getTags$0</excludedMethod>
                                <excludedMethod>lambda$initActivityUpdater$1</excludedMethod>
                                <excludedMethod>lambda$initSystemMessages$3</excludedMethod>
                                <excludedMethod>lambda$initSystemMessages$4</excludedMethod>
                                <excludedMethod>lambda$setMediaFiles$3</excludedMethod>
                                <excludedMethod>lambda$setTags$1</excludedMethod>
                                <excludedMethod>main</excludedMethod>
                                <excludedMethod>okResponse</excludedMethod>
                                <excludedMethod>profile</excludedMethod>
                                <excludedMethod>readUser</excludedMethod>
                                <excludedMethod>saveBodyPartAsFile</excludedMethod>
                                <excludedMethod>saveDataUriAsFile</excludedMethod>
                                <excludedMethod>setActivitiesCount</excludedMethod>
                                <excludedMethod>setAgeMax</excludedMethod>
                                <excludedMethod>setAgeMin</excludedMethod>
                                <excludedMethod>setFavouritesCount</excludedMethod>
                                <excludedMethod>setMediaFiles</excludedMethod>
                                <excludedMethod>setParticipantsMax</excludedMethod>
                                <excludedMethod>setParticipantsMin</excludedMethod>
                                <excludedMethod>setRatingsCount</excludedMethod>
                                <excludedMethod>setRatingsSum</excludedMethod>
                                <excludedMethod>setTags</excludedMethod>
                                <excludedMethod>setTimeMax</excludedMethod>
                                <excludedMethod>setTimeMin</excludedMethod>
                                <excludedMethod>toJson</excludedMethod>
                                <excludedMethod>toString</excludedMethod>
                                <excludedMethod>update</excludedMethod>
                                <excludedMethod>updateProperties</excludedMethod>
                            </excludedMethods>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>