---
components:
  schemas:
    deleted_product:
      description: ""
      properties:
        deleted:
          description: Always true for a deleted object
          enum:
            - true
          type: boolean
        id:
          description: Unique identifier for the object.
          maxLength: 5000
          type: string
        object:
          description:
            String representing the object's type. Objects of the same
            type share the same value.
          enum:
            - product
          type: string
      required:
        - deleted
        - id
        - object
      title: DeletedProduct
      type: object
      x-expandableFields: []
      x-resourceId: deleted_product
    product:
      description: |-
        Products describe the specific goods or services you offer to your customers.
        For example, you might offer a Standard and Premium version of your goods or service; each version would be a separate Product.
        They can be used in conjunction with [Prices](https://stripe.com/docs/api#prices) to configure pricing in Checkout and Subscriptions.

        Related guides: [Set up a subscription](https://stripe.com/docs/billing/subscriptions/set-up-subscription) or accept [one-time payments with Checkout](https://stripe.com/docs/payments/checkout/client#create-products) and more about [Products and Prices](https://stripe.com/docs/billing/prices-guide)
      properties:
        active:
          description: Whether the product is currently available for purchase.
          type: boolean
        created:
          description:
            Time at which the object was created. Measured in seconds since
            the Unix epoch.
          format: unix-time
          type: integer
        description:
          description:
            The product's description, meant to be displayable to the customer.
            Use this field to optionally store a long form explanation of the product
            being sold for your own rendering purposes.
          maxLength: 5000
          nullable: true
          type: string
        id:
          description: Unique identifier for the object.
          maxLength: 5000
          type: string
        images:
          description:
            A list of up to 8 URLs of images for this product, meant to
            be displayable to the customer.
          items:
            maxLength: 5000
            type: string
          type: array
        livemode:
          description:
            Has the value `true` if the object exists in live mode or the
            value `false` if the object exists in test mode.
          type: boolean
        metadata:
          additionalProperties:
            maxLength: 500
            type: string
          description:
            Set of [key-value pairs](https://stripe.com/docs/api/metadata)
            that you can attach to an object. This can be useful for storing additional
            information about the object in a structured format.
          type: object
        name:
          description:
            The product's name, meant to be displayable to the customer.
            Whenever this product is sold via a subscription, name will show up on
            associated invoice line item descriptions.
          maxLength: 5000
          type: string
        object:
          description:
            String representing the object's type. Objects of the same
            type share the same value.
          enum:
            - product
          type: string
        package_dimensions:
          "$ref": "#/components/schemas/package_dimensions"
          #          oneOf:
          #            - "$ref": "#/components/schemas/package_dimensions"
          #            - type: array
          #              items:
          #                type: string
          description: The dimensions of this product for shipping purposes.
          nullable: true
        shippable:
          description: Whether this product is shipped (i.e., physical goods).
          nullable: true
          type: boolean
        statement_descriptor:
          description:
            Extra information about a product which will appear on your
            customer's credit card statement. In the case that multiple products are
            billed at once, the first statement descriptor will be used.
          maxLength: 5000
          nullable: true
          type: string
        tax_code:
          type: string
          nullable: true
        #          anyOf:
        #            - maxLength: 5000
        #              type: string
        #            - "$ref": "#/components/schemas/tax_code"
        #          description: A [tax code](https://stripe.com/docs/tax/tax-codes) ID.
        #          nullable: true
        #          x-expansionResources:
        #            oneOf:
        #              - "$ref": "#/components/schemas/tax_code"
        unit_label:
          description:
            A label that represents units of this product in Stripe and
            on customers’ receipts and invoices. When set, this will be included in
            associated invoice line item descriptions.
          maxLength: 5000
          nullable: true
          type: string
        updated:
          description:
            Time at which the object was last updated. Measured in seconds
            since the Unix epoch.
          format: unix-time
          type: integer
        url:
          description: A URL of a publicly-accessible webpage for this product.
          maxLength: 2048
          nullable: true
          type: string
        attributes: # Added
          type: array
          items:
            type: string
        default_price: # Added
          type: string
          nullable: true
        marketing_features: # Added
          type: array
          items:
            type: object
            properties:
              name:
                type: string
        type: # Added
          type: string
      required:
        - active
        # - created
        # - id
        - images
        - livemode
        - metadata
        # - name
        - object
        # - updated
      title: Product
      type: object
      x-expandableFields:
        - package_dimensions
        - tax_code
      x-resourceId: product
    package_dimensions:
      description: ""
      nullable: true
      properties:
        height:
          description: Height, in inches.
          type: number
        length:
          description: Length, in inches.
          type: number
        weight:
          description: Weight, in ounces.
          type: number
        width:
          description: Width, in inches.
          type: number
      required:
        - height
        - length
        - weight
        - width
      title: PackageDimensions
      type: object
      x-expandableFields: []
    tax_code:
      nullable: true
      description:
        "[Tax codes](https://stripe.com/docs/tax/tax-codes) classify goods
        and services for tax purposes."
      properties:
        description:
          description:
            A detailed description of which types of products the tax code
            represents.
          maxLength: 5000
          type: string
        id:
          description: Unique identifier for the object.
          maxLength: 5000
          type: string
        name:
          description: A short name for the tax code.
          maxLength: 5000
          type: string
        object:
          description:
            String representing the object's type. Objects of the same
            type share the same value.
          enum:
            - tax_code
          type: string
      required:
        - description
        - id
        - name
        - object
      title: TaxProductResourceTaxCode
      type: object
      x-expandableFields: []
      x-resourceId: tax_code
  securitySchemes:
    basicAuth:
      description:
        "Basic HTTP authentication. Allowed headers-- Authorization: Basic
        <api_key> | Authorization: Basic <base64 hash of `api_key:`>"
      scheme: basic
      type: http
    bearerAuth:
      bearerFormat: auth-scheme
      description:
        "Bearer HTTP authentication. Allowed headers-- Authorization: Bearer
        <api_key>"
      scheme: bearer
      type: http
info:
  contact:
    email: dev-platform@stripe.com
    name: Stripe Dev Platform Team
    url: https://stripe.com
  description:
    The Stripe REST API. Please see https://stripe.com/docs/api for more
    details.
  termsOfService: https://stripe.com/us/terms/
  title: Stripe API
  version: "2020-08-27"
  x-stripeSpecFilename: spec3
openapi: 3.0.0
paths:
  /v1/products:
    post:
      summary: Create a product
      description: Create a new product object.
      operationId: PostProducts
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: |
                    The product’s name, meant to be displayable to the customer.
                active:
                  type: boolean
                  description: |
                    Whether the product is currently available for purchase. Default is `true`.
                description:
                  type: string
                  description: |
                    A description of the product, meant to be displayable to the customer.
                id:
                  type: string
                  description: |
                    A unique identifier you can assign to this product (optional).
                tax_code:
                  type: string
                  description: |
                    A tax code ID to assign to this product for tax calculation purposes.
                default_price_data:
                  type: object
                  required: 
                    - currency
                  description: |
                    Data to create a Price object directly and set it as the default price for this product.
                  properties:
                    currency:
                      type: string
                      description: Three-letter ISO currency code in lowercase (e.g., `usd`).
                    recurring:
                      type: object
                      required:
                        - interval
                      description: Specifies billing cycle if the price is recurring.
                      properties:
                        interval:
                          type: string
                          enum: [day, week, month, year]
                          description: The frequency with which a subscription is billed.
                        interval_count:
                          type: integer
                          description: Number of intervals between subscription billings.
                    tax_behavior:
                      type: string
                      enum: [exclusive, inclusive, unspecified]
                    unit_amount:
                      type: integer
                      description: Only one of unit_amount, unit_amount_decimal, or custom_unit_amount is required.
                    unit_amount_decimal:
                      type: number
                    custom_unit_amount:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                              description: Pass in true to enable custom_unit_amount, otherwise omit custom_unit_amount.
                            maximum:
                              type: integer
                            minimum:
                              type: integer
                            preset:
                              type: integer
                              description: The starting unit amount which can be updated by the customer.

                images:
                  type: array
                  items:
                    type: string
                    format: uri
                  maxItems: 8
                  description: |
                    A list of up to 8 URLs of images for the product.
                marketing_features:
                  type: array
                  maxItems: 15
                  description: List of marketing features shown for this product.
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Feature name.
                package_dimensions:
                  type: object
                  description: Dimensions of this product for shipping purposes.
                  properties:
                    height:
                      type: number
                      format: float
                      description: Height in inches, accurate to two decimal places.
                    length:
                      type: number
                      format: float
                      description: Length in inches.
                    weight:
                      type: number
                      format: float
                      description: Weight in ounces.
                    width:
                      type: number
                      format: float
                      description: Width in inches.
                shippable:
                  type: boolean
                  description: |
                    Whether this product is a physical, shippable item.
                statement_descriptor:
                  type: string
                  maxLength: 22
                  description: |
                    Extra information about a product that will appear on your customer’s credit card statement. 
                unit_label:
                  type: string
                  description: |
                    A label that represents units of this product, such as “seat” or “license”.
                url:
                  type: string
                  format: uri
                  description: |
                    A publicly available webpage for this product.
                
                
                
      x-dependencies:
        - AllOrNone([package_dimensions[height]], [package_dimensions[length]], [package_dimensions[weight]], [package_dimensions[width]]);
        - AllOrNone([default_price_data[currency]], [default_price_data[unit_amount]]);
      responses:
        "200":
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/product"
          description: Successful response.
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    required:
                      - code
                      - message
                      - type
                    properties:
                      code:
                        type: string
                        example: parameter_missing
                        description: Machine-readable error code.
                      doc_url:
                        type: string
                        format: uri
                        description: Link to Stripe documentation for this error.
                        example: https://stripe.com/docs/error-codes/parameter-missing
                      message:
                        type: string
                        description: Human-readable error message providing more details about the error.
                        example:
                          Missing required param: name.
                      param:
                        type: string
                        nullable: true
                        description: The name of the parameter related to the error, if applicable.
                        example: name
                      request_log_url:
                        type: string
                        format: uri
                        description: Link to the request log entry in the Stripe Dashboard.
                        example: https://dashboard.stripe.com/test/logs/req_hooQodrQWTeFut?t=1759996053
                      type:
                        type: string
                        description: The type of error (e.g., `api_error`, `invalid_request_error`).
                        example: invalid_request_error
        '401':
          description: Unauthorized - missing or invalid API key
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    required:
                      - message
                      - type
                    properties:
                      message:
                        type: string
                        description: Human-readable message describing the authentication error.
                        example: >
                          You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.
                      type:
                        type: string
                        description: The type of error. Usually `invalid_request_error` for authentication failures.
                        example: invalid_request_error
security:
  - basicAuth: []
  - bearerAuth: []
servers:
  - url: https://api.stripe.com/
