<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>es.us.isa.httpmutator.experiment.services</groupId>
        <artifactId>mt_jdk11</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <groupId>mt.market</groupId>
    <artifactId>mt-market</artifactId>
    <packaging>jar</packaging>

    <url>http://maven.apache.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Swagger 2.x (io.swagger:*)  1.6.16 -->
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-core</artifactId>
                <version>1.6.16</version>
            </dependency>
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-models</artifactId>
                <version>1.6.16</version>
            </dependency>
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-parser</artifactId>
                <version>1.0.75</version>
            </dependency>

            <!-- OpenAPI 3.x (io.swagger.core.v3:*) -->
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-models</artifactId>
                <version>2.2.21</version>
            </dependency>
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-annotations</artifactId>
                <version>2.2.21</version>
            </dependency>
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-core</artifactId>
                <version>2.2.21</version>
            </dependency>
            <dependency>
                <groupId>io.swagger.parser.v3</groupId>
                <artifactId>swagger-parser</artifactId>
                <version>2.1.22</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-models</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-models</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.lukyanets</groupId>
            <artifactId>market-core</artifactId>
            <version>0.1.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.lukyanets</groupId>
            <artifactId>market-web</artifactId>
            <version>0.1.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.lukyanets</groupId>
            <artifactId>market-rest</artifactId>
            <version>0.1.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.lukyanets</groupId>
            <artifactId>market-coverage</artifactId>
            <version>0.1.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <version>2.4.3</version>
            <exclusions>
                <exclusion>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
            <version>2.4.3</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>post-register</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-maven</artifactId>
                        <configuration>
                            <targetTests>
                                <param>mt.market.MarketEndpointTest</param>
                            </targetTests>
                            <targetClasses>
                                <param>market.*</param>
                            </targetClasses>
                            <excludedMethods>
                                <excludedMethod>accessDeniedException</excludedMethod>
                                <excludedMethod>customNotValidException</excludedMethod>
                                <excludedMethod>equals</excludedMethod>
                                <excludedMethod>getCart</excludedMethod>
                                <excludedMethod>getCityAndRegion</excludedMethod>
                                <excludedMethod>getCustomer</excludedMethod>
                                <excludedMethod>getUserAccount</excludedMethod>
                                <excludedMethod>hashCode</excludedMethod>
                                <excludedMethod>otherExceptions</excludedMethod>
                                <excludedMethod>setCart</excludedMethod>
                                <excludedMethod>setCityAndRegion</excludedMethod>
                                <excludedMethod>setColor</excludedMethod>
                                <excludedMethod>setContacts</excludedMethod>
                                <excludedMethod>setDescription</excludedMethod>
                                <excludedMethod>setRoles</excludedMethod>
                                <excludedMethod>setSubtitle</excludedMethod>
                                <excludedMethod>unknownEntityException</excludedMethod>
                            </excludedMethods>
                            <excludedClasses>
                                <excludedClass>market.FixturesFactory</excludedClass>
                                <excludedClass>market.WebSecurityConfig</excludedClass>
                                <excludedClass>market.controller.CartModelHelper</excludedClass>
                                <excludedClass>market.controller.SpringExceptionHandler</excludedClass>
                                <excludedClass>market.controller.backend.BackendController</excludedClass>
                                <excludedClass>market.controller.backend.DistilleryController</excludedClass>
                                <excludedClass>market.controller.backend.OrdersController</excludedClass>
                                <excludedClass>market.controller.backend.ProductController</excludedClass>
                                <excludedClass>market.controller.backend.RegionController</excludedClass>
                                <excludedClass>market.controller.backend.StorageController</excludedClass>
                                <excludedClass>market.controller.frontend.CartController</excludedClass>
                                <excludedClass>market.controller.frontend.CheckoutController</excludedClass>
                                <excludedClass>market.controller.frontend.CustomerController</excludedClass>
                                <excludedClass>market.controller.frontend.FrontendController</excludedClass>
                                <excludedClass>market.controller.frontend.ShowcaseController</excludedClass>
                                <excludedClass>market.domain.Bill</excludedClass>
                                <excludedClass>market.domain.Bill$Builder</excludedClass>
                                <excludedClass>market.domain.Cart</excludedClass>
                                <excludedClass>market.domain.Cart$Builder</excludedClass>
                                <excludedClass>market.domain.CartItem</excludedClass>
                                <excludedClass>market.domain.CartItemId</excludedClass>
                                <excludedClass>market.domain.Distillery</excludedClass>
                                <excludedClass>market.domain.Distillery$Builder</excludedClass>
                                <excludedClass>market.domain.Order</excludedClass>
                                <excludedClass>market.domain.Order$Builder</excludedClass>
                                <excludedClass>market.domain.OrderedProduct</excludedClass>
                                <excludedClass>market.domain.OrderedProduct$Builder</excludedClass>
                                <excludedClass>market.domain.OrderedProductId</excludedClass>
                                <excludedClass>market.domain.Product</excludedClass>
                                <excludedClass>market.domain.Product$Builder</excludedClass>
                                <excludedClass>market.domain.Region</excludedClass>
                                <excludedClass>market.domain.Role</excludedClass>
                                <excludedClass>market.dto.BillDTO</excludedClass>
                                <excludedClass>market.dto.CartDTO</excludedClass>
                                <excludedClass>market.dto.CartItemDTO</excludedClass>
                                <excludedClass>market.dto.ContactsDTO</excludedClass>
                                <excludedClass>market.dto.CreditCardDTO</excludedClass>
                                <excludedClass>market.dto.DistilleryDTO</excludedClass>
                                <excludedClass>market.dto.OrderDTO</excludedClass>
                                <excludedClass>market.dto.OrderedProductDTO</excludedClass>
                                <excludedClass>market.dto.ProductDTO</excludedClass>
                                <excludedClass>market.dto.ProductPreviewDTO</excludedClass>
                                <excludedClass>market.dto.RegionDTO</excludedClass>
                                <excludedClass>market.dto.assembler.BillDtoAssembler</excludedClass>
                                <excludedClass>market.dto.assembler.CartDtoAssembler</excludedClass>
                                <excludedClass>market.dto.assembler.ContactsDtoAssembler</excludedClass>
                                <excludedClass>market.dto.assembler.DistilleryDtoAssembler</excludedClass>
                                <excludedClass>market.dto.assembler.OrderDtoAssembler</excludedClass>
                                <excludedClass>market.dto.assembler.OrderedProductDtoAssembler</excludedClass>
                                <excludedClass>market.dto.assembler.ProductDtoAssembler</excludedClass>
                                <excludedClass>market.dto.assembler.ProductPreviewAssembler</excludedClass>
                                <excludedClass>market.dto.assembler.RegionDtoAssembler</excludedClass>
                                <excludedClass>market.dto.exception.ValidationErrorDTO</excludedClass>
                                <excludedClass>market.exception.CustomNotValidException</excludedClass>
                                <excludedClass>market.exception.UnknownEntityException</excludedClass>
                                <excludedClass>market.interceptors.SessionCartInterceptor</excludedClass>
                                <excludedClass>market.properties.MarketProperties</excludedClass>
                                <excludedClass>market.properties.PaginationProperties</excludedClass>
                                <excludedClass>market.properties.PaginationProperties$Builder</excludedClass>
                                <excludedClass>market.rest.CartRestController</excludedClass>
                                <excludedClass>market.rest.ContactsRestController</excludedClass>
                                <excludedClass>market.rest.OrdersRestController</excludedClass>
                                <excludedClass>market.rest.ProductsRestController</excludedClass>
                                <excludedClass>market.security.CustomAuthenticationSuccessHandler</excludedClass>
                                <excludedClass>market.service.impl.CartServiceImpl</excludedClass>
                                <excludedClass>market.service.impl.ContactsServiceImpl</excludedClass>
                                <excludedClass>market.service.impl.DistilleryServiceImpl</excludedClass>
                                <excludedClass>market.service.impl.OrderServiceImpl</excludedClass>
                                <excludedClass>market.service.impl.ProductServiceImpl</excludedClass>
                                <excludedClass>market.service.impl.RegionServiceImpl</excludedClass>
                                <excludedClass>market.sorting.AbstractSorter</excludedClass>
                                <excludedClass>market.sorting.OrderSorting</excludedClass>
                                <excludedClass>market.sorting.ProductBackendSorting</excludedClass>
                                <excludedClass>market.sorting.SortingValuesDTO</excludedClass>
                                <excludedClass>market.sorting.StorageSorting</excludedClass>
                            </excludedClasses>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>put-customerCart</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.pitest</groupId>
                        <artifactId>pitest-maven</artifactId>
                        <configuration>
                            <targetTests>
                                <param>mt.market.MarketEndpointTest</param>
                            </targetTests>
                            <targetClasses>
                                <param>market.*</param>
                            </targetClasses>
                            <excludedClasses>
                                <excludedClass>market.FixturesFactory</excludedClass>
                                <excludedClass>market.WebSecurityConfig</excludedClass>
                                <excludedClass>market.controller.CartModelHelper</excludedClass>
                                <excludedClass>market.controller.SpringExceptionHandler</excludedClass>
                                <excludedClass>market.controller.backend.BackendController</excludedClass>
                                <excludedClass>market.controller.backend.DistilleryController</excludedClass>
                                <excludedClass>market.controller.backend.OrdersController</excludedClass>
                                <excludedClass>market.controller.backend.ProductController</excludedClass>
                                <excludedClass>market.controller.backend.RegionController</excludedClass>
                                <excludedClass>market.controller.backend.StorageController</excludedClass>
                                <excludedClass>market.controller.frontend.CartController</excludedClass>
                                <excludedClass>market.controller.frontend.CheckoutController</excludedClass>
                                <excludedClass>market.controller.frontend.CustomerController</excludedClass>
                                <excludedClass>market.controller.frontend.FrontendController</excludedClass>
                                <excludedClass>market.controller.frontend.ShowcaseController</excludedClass>
                                <excludedClass>market.domain.Bill</excludedClass>
                                <excludedClass>market.domain.Bill$Builder</excludedClass>
                                <excludedClass>market.domain.Cart$Builder</excludedClass>
                                <excludedClass>market.domain.CartItemId</excludedClass>
                                <excludedClass>market.domain.Contacts</excludedClass>
                                <excludedClass>market.domain.Contacts$Builder</excludedClass>
                                <excludedClass>market.domain.Distillery</excludedClass>
                                <excludedClass>market.domain.Distillery$Builder</excludedClass>
                                <excludedClass>market.domain.Order</excludedClass>
                                <excludedClass>market.domain.Order$Builder</excludedClass>
                                <excludedClass>market.domain.OrderedProduct</excludedClass>
                                <excludedClass>market.domain.OrderedProduct$Builder</excludedClass>
                                <excludedClass>market.domain.OrderedProductId</excludedClass>
                                <excludedClass>market.domain.Product$Builder</excludedClass>
                                <excludedClass>market.domain.Region</excludedClass>
                                <excludedClass>market.domain.Role</excludedClass>
                                <excludedClass>market.domain.UserAccount$Builder</excludedClass>
                                <excludedClass>market.dto.BillDTO</excludedClass>
                                <excludedClass>market.dto.ContactsDTO</excludedClass>
                                <excludedClass>market.dto.CreditCardDTO</excludedClass>
                                <excludedClass>market.dto.DistilleryDTO</excludedClass>
                                <excludedClass>market.dto.OrderDTO</excludedClass>
                                <excludedClass>market.dto.OrderedProductDTO</excludedClass>
                                <excludedClass>market.dto.ProductDTO</excludedClass>
                                <excludedClass>market.dto.ProductPreviewDTO</excludedClass>
                                <excludedClass>market.dto.RegionDTO</excludedClass>
                                <excludedClass>market.dto.UserDTO</excludedClass>
                                <excludedClass>market.dto.assembler.BillDtoAssembler</excludedClass>
                                <excludedClass>market.dto.assembler.ContactsDtoAssembler</excludedClass>
                                <excludedClass>market.dto.assembler.DistilleryDtoAssembler</excludedClass>
                                <excludedClass>market.dto.assembler.OrderDtoAssembler</excludedClass>
                                <excludedClass>market.dto.assembler.OrderedProductDtoAssembler</excludedClass>
                                <excludedClass>market.dto.assembler.ProductDtoAssembler</excludedClass>
                                <excludedClass>market.dto.assembler.ProductPreviewAssembler</excludedClass>
                                <excludedClass>market.dto.assembler.RegionDtoAssembler</excludedClass>
                                <excludedClass>market.dto.assembler.UserAccountDtoAssembler</excludedClass>
                                <excludedClass>market.dto.exception.ValidationErrorDTO</excludedClass>
                                <excludedClass>market.exception.UnknownEntityException</excludedClass>
                                <excludedClass>market.interceptors.SessionCartInterceptor</excludedClass>
                                <excludedClass>market.properties.PaginationProperties</excludedClass>
                                <excludedClass>market.properties.PaginationProperties$Builder</excludedClass>
                                <excludedClass>market.rest.ContactsRestController</excludedClass>
                                <excludedClass>market.rest.CustomerRestController</excludedClass>
                                <excludedClass>market.rest.OrdersRestController</excludedClass>
                                <excludedClass>market.rest.ProductsRestController</excludedClass>
                                <excludedClass>market.security.AuthenticationService</excludedClass>
                                <excludedClass>market.security.CustomAuthenticationSuccessHandler</excludedClass>
                                <excludedClass>market.service.impl.ContactsServiceImpl</excludedClass>
                                <excludedClass>market.service.impl.DistilleryServiceImpl</excludedClass>
                                <excludedClass>market.service.impl.OrderServiceImpl</excludedClass>
                                <excludedClass>market.service.impl.RegionServiceImpl</excludedClass>
                                <excludedClass>market.sorting.AbstractSorter</excludedClass>
                                <excludedClass>market.sorting.OrderSorting</excludedClass>
                                <excludedClass>market.sorting.ProductBackendSorting</excludedClass>
                                <excludedClass>market.sorting.SortingValuesDTO</excludedClass>
                                <excludedClass>market.sorting.StorageSorting</excludedClass>
                            </excludedClasses>
                            <excludedMethods>
                                <excludedMethod>addAllToCart</excludedMethod>
                                <excludedMethod>clear</excludedMethod>
                                <excludedMethod>clearCart</excludedMethod>
                                <excludedMethod>containsProductId</excludedMethod>
                                <excludedMethod>create</excludedMethod>
                                <excludedMethod>createCart</excludedMethod>
                                <excludedMethod>customNotValidException</excludedMethod>
                                <excludedMethod>delete</excludedMethod>
                                <excludedMethod>equals</excludedMethod>
                                <excludedMethod>findAll</excludedMethod>
                                <excludedMethod>findByAvailability</excludedMethod>
                                <excludedMethod>findByDistillery</excludedMethod>
                                <excludedMethod>findById</excludedMethod>
                                <excludedMethod>findByRegion</excludedMethod>
                                <excludedMethod>getAge</excludedMethod>
                                <excludedMethod>getAlcohol</excludedMethod>
                                <excludedMethod>getCart</excludedMethod>
                                <excludedMethod>getContacts</excludedMethod>
                                <excludedMethod>getDistillery</excludedMethod>
                                <excludedMethod>getName</excludedMethod>
                                <excludedMethod>getVolume</excludedMethod>
                                <excludedMethod>hashCode</excludedMethod>
                                <excludedMethod>lambda$containsProductId$0</excludedMethod>
                                <excludedMethod>lambda$getCartOrCreate$0</excludedMethod>
                                <excludedMethod>lambda$payByCard$0</excludedMethod>
                                <excludedMethod>lambda$removeItem$0</excludedMethod>
                                <excludedMethod>lambda$updateAvailability$1</excludedMethod>
                                <excludedMethod>otherExceptions</excludedMethod>
                                <excludedMethod>payByCard</excludedMethod>
                                <excludedMethod>processValidationError</excludedMethod>
                                <excludedMethod>saveInternal</excludedMethod>
                                <excludedMethod>setColor</excludedMethod>
                                <excludedMethod>setDelivery</excludedMethod>
                                <excludedMethod>setDescription</excludedMethod>
                                <excludedMethod>setProduct</excludedMethod>
                                <excludedMethod>setSubtitle</excludedMethod>
                                <excludedMethod>toDomain</excludedMethod>
                                <excludedMethod>updateAvailability</excludedMethod>
                            </excludedMethods>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
